service.message: Hello, World
server:
  port: 8080
graphql:
  tools:
    schema-location-pattern: "graphql/*.graphqls"
  servlet:
    actuator-metrics: true
    websocket.enabled: false
    corsEnabled: true
    mapping: /api/v1/demo/graphql
# 调试页面1
graphiql:
  enabled: true
  mapping: /api/v1/demo/graphql.html
  cdn:
    enabled: true
  endpoint:
    graphql: ./graphql
# 调试页面2
graphql.playground:
  enabled: true
  mapping: /api/v1/demo/playground
  endpoint: ./graphql
  cdn:
    enabled: true
# 数据库配置
spring.datasource:
  url: jdbc:mysql://192.168.6.6:3306/tester_java?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
  username: tester
  password: tester
  hikari:
    max-lifetime: 60000
# 同步数据结构
spring.jpa.hibernate.ddl-auto: update
spring:
  # 忽略关键字命名字段
  jpa:
    # true: 调试sql语句
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
# jwt相关配置
security:
  jwt:
    token:
      # 用户token密钥
      secret: hahaha
      # 管理员token密钥
      secretAdmin: lalala
      # 用户rsa私钥
      key-user: -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIvzmdWOR4dy7A
        GakUfpkGrCEAhZ4ZQrADqGm/7waWx9Hz4nHBDbXBqhPlCn19eLSI3Blt480b89+C
        eZW8iAFWTkDYx1PXvFfPv3yrOO9Ejh1gggB2JaAQGuKUawuWYU6t8fAx6Qi5xYC7
        OLOggqHprJyqnTKmsDY+HELf1w6RM7qe6kaNBpT8Vm5h4vUbF0BUVCIFY2IssAeu
        UdMBGyyFYnV8uqvlnpzPgV9q0aSQF4dQzhNGjefymQlLW2D/uWoKEgqIITbNwW8g
        aC5n6eYGMyUmL+e/cK7Q9LyNYKuPU3ogDXqjVLqoTIsWQnaNxPH1oxKr6LP9Is/T
        aTch3lBhAgMBAAECggEBAMUw0e91+jc7G3knu6aeFMMxIdnZZst5blypefdHXDmQ
        XvQqY4M3bGqoHpLGEy7E+tHVIkWHl1r123/W3vcqweV9SMWoRvuLztYLSvMGIkI9
        Ny4thTaJDwnC3v7bh65YN2k2VrMwLZoOH73InOn2aAWZwOr3L2H9hcrNCAPIxE5r
        vGdp0NfB7t3KVQV7yEsVuSqee4b/4g3EjE4GWAGrVNZBvhlKVCAVNyecfoQVkTz5
        38tCOJ88z5JyEWsrzvsnLrFJ1U3pf5cf/J/cof9DiFpGEFzO+5rStWPX8reQx6pr
        ihjFlNXzZcBkCw72k2Vnvj55B/ESKL9kZkE2wxmE0WECgYEA5WhEuNE8SsrvrGLQ
        AjuGIkJN6h8sA0fZPB3x+GUnuF5XmFAHywgB0lgsbV9Zy6v32WsXUXm6Nfp8PFBj
        K+EjZbdd8OCfAkIn6/5MSmz30DNRxhGITUqZabKRWfZT6zpVxVCM23FVYXs/jwU7
        RaXL3SyCHv/RckGhO8XkUV5Bc2sCgYEA4ARz5HMmXMXeTNx9b53xv635NtPg3d6L
        rRvM+w75UDKIWWysVc0Qd2IIytlIXGV2oyfosCt7KgDCVzggF7JNMHpPCRzO6qQY
        8Msoo+SnjHapFWPfNgPpPlkoWIHZL3FCmHKsT42WILFSi9FlOJ7zDdNgG24kc7Rk
        MUA1kf/FimMCgYBZE0Zz2NKnW+r6LZgE9eXcUZB9UsM9Nt2zyRDWWTi2DvPGMXUF
        McO7T/9YLIjqW4iuRDXWrgROx0cMCE6pkA61hSCV0jILp3Jm4OPwliUXE4Yx+UbK
        dCfjcbGck9f74zfAmMlIv9XeNwPz3Z0pKvpgk9KmhMBns/IOCoXfzlBtpwKBgQDT
        WYAZrcYoywnTjEbP8rztMe8pGjdSPC+db9gxmUwArNxVOiFRhfoeGCDheKQ7gAKx
        JerzouI9m5+++BXXJYKL1SkSGNrjJ1TcgV/jWMv2ytD1fFdQN9pr12QoNMG6b+n7
        uFz3ZUaZq5KMlU8hX11C0wUefAjqHOxWRxUDnMM7rwKBgH96UkH5Tito1lx6vPgb
        L3ozTIqlokBySEOdYWaCrsR1sDTai+b6fjIXcjRXU7+NDCQKD7JlbYvaOD2Jsz/u
        fhNnyr/dH+zXwMhEeT6zSKj9IwJ6f+2TRdq4HRbnh1ZSPq3R0BvlxL1HWOfE+5uo
        Gf7C377OrZo5ZhmeVqiqeHip
        -----END PRIVATE KEY-----
      # 用户rsa公钥
      pub-user: -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyL85nVjkeHcuwBmpFH6Z
        BqwhAIWeGUKwA6hpv+8GlsfR8+JxwQ21waoT5Qp9fXi0iNwZbePNG/PfgnmVvIgB
        Vk5A2MdT17xXz798qzjvRI4dYIIAdiWgEBrilGsLlmFOrfHwMekIucWAuzizoIKh
        6aycqp0yprA2PhxC39cOkTO6nupGjQaU/FZuYeL1GxdAVFQiBWNiLLAHrlHTARss
        hWJ1fLqr5Z6cz4FfatGkkBeHUM4TRo3n8pkJS1tg/7lqChIKiCE2zcFvIGguZ+nm
        BjMlJi/nv3Cu0PS8jWCrj1N6IA16o1S6qEyLFkJ2jcTx9aMSq+iz/SLP02k3Id5Q
        YQIDAQAB
        -----END PUBLIC KEY-----
      # 管理员rsa私钥
      key-admin: -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCsStkTtrvov6gi
        sOxpR+tY3Zpj0ilNX2gbJQ3hzcuhpu8TW9Q4wBjQdv2xcTeeDGRzyyvg/fdLzmLz
        sEx1jCNgCuGRDeyisIAUAQWP8dMFolMLu9f0+Bh5RGEN0X+eX3DvNTwJYOqegoLe
        yZ6M0s+XHjB13pv15EL2bDh8l4nZ/6JGDKV3jbVydIh0hqtXp0Flfa78ewC6F8Wb
        fzwmBM18puG/+cz6Y0QsQGboUww9dCK9/8mogmbfhqRqU/5UVpvAANifq2cy8Qtn
        baCgRQUVzvvSXjLHNQOarx2FCYwiIhdSYW5MzIO4wdX2iFOMy+k4vQucwNjSKpnW
        TnbrpGd1AgMBAAECggEAewoQsAVleDe2iN+0VRMpPRM0eGjTWg/yNsBlg4YGD/E4
        9qgzjDuS/Pyc+6UQxOuwqQjE0y5K9nXzMHgMgj2L3cCniYFaJmzJan+4Sy21N2bO
        y6hf9u9d+uwcK1QbQSyDaDCqKUBvDLfDYfq2IXdDDHZgwSwyUI2sTHLIfCF0Lps2
        Lom4v5o6NRcPqy6d0j+Ghc6spY2cks9FOPsoaodw2MdT83nGOHvD6jr7t9aq/UaB
        u8zOMyYlfaVxmA0kNLxVdMgxn2wji94XhjJ+XQgbqCTGdfXQaHwey4fOiXhLHHdz
        GbeybGF1Tfvvn4mAIuBjoUFntOjtZkBRVqB7dhRNwQKBgQDb3cC2FZ2gBnAqH9Uc
        cJSSJHDe+kM/cl05OlYzVBuadfMybMyGeR5md0ozRvT0j7UJvdSx1N9u2nDxFk2f
        jjM/ITu/11E+9oWpuZjV+6OSYq/BICwcdicjwwfAbCz3b4EV5dQsDmUNVBrVjjhp
        ff8upgHLjmM2dEWuoP4GSePi6QKBgQDIm4+Dd1HR7X4RizGRss6BDzPELn1GsASL
        WY4cE1eSyohWd97AezKSmxhpEPjoGiwxnQIGgmhLsuPBBDzTnyKYT+K4JLTaWzHf
        9yNYtWunXK9eFP2YscIe8cvefCVWb432P4qfHEirPvVSMhEk4Oegc3tj0Pf7F559
        wFkPWlmQrQKBgCOpdkaSfvyjzrGmdCSmxhJmQsCICzxRSnmr0quEqu2E0CuPpiTx
        pFKuaqSij7zTSmQIHGWzx4HtgIA6Q+DrabiFpXFadV0nE0sSRY3/wOpPg35pv33m
        VDbivXEimrCPr3pjyuRSeWWODMQyy0ehHjDs0EG6GLGObncCufE/Lu1xAoGAEUXr
        vosonWXQpBwTIZN+2nf/ohXKrap8Sa9lYB9+O+J6iM97e6FgAmWeXXWbqQiP45m8
        Uekqp9H4cGc4AZTDOtAuGmL2u5J8oec6wOmmIlwFsZknGN29dEKnpjmUUXP7ikeA
        XSDnVO9v2ir7dOx0pUksR7T3lUQ8XmGQiZTi/2UCgYA3j4VyfC5i/m40qjC7smGl
        fINF8w6pPUSByuPd9FXjCQOqIarL/gT7uLVTkpSgAsmox3uvmXadcRbBePDdPhMo
        tVnSrwBC9Wtvt5jdtIpSCGWJvVjTLuX1R0MPaTQVavZUzFN84TsLYx2rPKU1Et8+
        bGbOmyNMO7AuZOYuXJYnuA==
        -----END PRIVATE KEY-----
      # 管理员rsa公钥
      pub-admin: -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArErZE7a76L+oIrDsaUfr
        WN2aY9IpTV9oGyUN4c3LoabvE1vUOMAY0Hb9sXE3ngxkc8sr4P33S85i87BMdYwj
        YArhkQ3sorCAFAEFj/HTBaJTC7vX9PgYeURhDdF/nl9w7zU8CWDqnoKC3smejNLP
        lx4wdd6b9eRC9mw4fJeJ2f+iRgyld421cnSIdIarV6dBZX2u/HsAuhfFm388JgTN
        fKbhv/nM+mNELEBm6FMMPXQivf/JqIJm34akalP+VFabwADYn6tnMvELZ22goEUF
        Fc770l4yxzUDmq8dhQmMIiIXUmFuTMyDuMHV9ohTjMvpOL0LnMDY0iqZ1k5266Rn
        dQIDAQAB
        -----END PUBLIC KEY-----
